### PR TITLE
update astropy helpers

### PR DESCRIPTION
**Pull request by keflavich**

### CODE REVIEW

**Comment by astrofrog** [comment]
Seems to work but you should also copy ``ah_bootstrap.py`` to the root level of ``radio-beam`` to update that file. Thanks!

**Comment by astrofrog** [comment]
Also, can you enable Python 3.6 on Travis? (since that would catch this issue)

**Comment by keflavich** [comment]
I'm not sure what happened to the CI builds, they don't seem to be running?

**Comment by keflavich** [comment]
Old versions of numpy (1.7, 1.8) are failing.  I'm going to drop them; they're ancient.

**Pull request merged**
