### PR TITLE
Trap obscure flavor of CASA header

### PR DESCRIPTION
**Pull request by low-sky**
Sometimes (old?) CASA seems to write out headers with AIPS-like HISTORY beam information (but with different line structures).  These are hanging out in the [image archives](http://jvo.nao.ac.jp/portal/alma/archive.do).  

I've included a sample file in the `data` directory on `test` called `m83.moment0.fits`

### CODE REVIEW

**Comment by e-koch** [comment]
That header has no history of running `exportfits`, so maybe the archive is doing something else? The reduction was done in 4.2.1, so `exportfits` should be writing out the beam correctly in to a FITS header.

Also, we should probably keep names like `from_casa_header` reserved for instantiating from CASA images.

**Comment by low-sky** [comment]
Perhaps `from_casa_fits_history` or `from_history` and merge the AIPS style and CASA style?

**Comment by low-sky** [comment]
@keflavich -- Ready for review?
Also is there any chance @e-koch could get write access?

**Comment by e-koch** [comment]
@low-sky - Can you also make a version of `m83.moment0.fits` with just the header? I don't think we'll need the data for testing in `radio_beam` (when we actually turn on CI).

**Comment by keflavich** [comment]
:+1: 
Would be great to turn on CI too.  I'll merge this now, but if @e-koch wants to turn on CI... he now has write permission.

**Comment by e-koch** [comment]
Thanks! Will do soonish.

**Pull request merged**
