### PR TITLE
Pass pixscale to ellipse_to_plot

### PR DESCRIPTION
**Pull request by e-koch**
`ellipse_to_plot` was never finished. Since we pass `pixscale` in everywhere else, it should be passed instead of `wcs`.

Other changes:
* skipping doc tests in `index.rst`
* Added testing for newer numpy versions
* Removed the make file in `tests/data/` which was accidently copied over from the `spectral-cube`

### CODE REVIEW

**Comment by keflavich** [comment]
@e-koch don't deprecate older versions of numpy - we actually have to support np1.7 to support CASA  (!!!! =( !@#$!@#$)

(see #312)

**Comment by e-koch** [comment]
Well crap. Alright.

**Comment by keflavich** [comment]
@e-koch my fight with CASA will likely be to the death.  I think the changes you're making should be fine - what was going wrong with older versions of numpy?  Let's try to find a workaround here rather than wait on CASA to wake up

**Comment by e-koch** [comment]
Ah, this shouldn't be here! https://github.com/radio-astro-tools/radio_beam/blob/master/radio_beam/tests/data/Makefile

There shouldn't be any conflicts without this.

**Comment by keflavich** [comment]
No, the most important is numpy 1.7 + python 2.7, which is what CASA <= 5.0 runs on

**Pull request merged**
