### PR TITLE
Add a tool for reading BinTableHDU beams

### PR DESCRIPTION
**Pull request by keflavich**
These are the new types of beam tables produced by tclean.  They are more
accurate, since they tell you the beam *per image*, but that's also annoying to
deal with since it basically renders the idea of a single SpectralCube invalid.
This approach will try to make a single beam from a table given some tolerance,
which ought to be good enough for many cubes (the majority?), but not for
mine...

For the more general case of a truly varying beam with channel, the Beam object
should just be directly instantiated.

cc @e-koch, @low-sky: feedback on API?  default tolerance?

### CODE REVIEW

**Comment by low-sky** [comment]
This looks good for a first run at the problem.  The only one I have concerns about is the `BPA` mean since the mean of an angle isn't necessarily what you think.  This might not be anywhere near right, but the approach would probably look more like a vector average than a scalar:

    meanmajx = mean(BMAJ*cos(BPA))
    meanmajy = mean(BMAJ*sin(BPA))
    meanminx = mean(BMIN*cos(BPA))
    meanminy = mean(BMIN*sin(BPA))
    BMAJ = (meanmajx**2 + meanmajy**2)**0.5
    BMIN = (meanminx**2 + meanminy**2)**0.5
    BPA = np.arctan2(meanmajy, meanmajx)

Since PAs are degenerate and only run from [-π/2 to π/2], there might be a factor of 2 in there on the cos(BPA) terms...  Argh.  So foggy headed.  

In the future it seems like one can develop the the idea of a beam function that returns beams vs. frequency using these values a la `jtok_equivalancies` and similar functionality.  This could easily require some sensible embedding in `SpectralCube` so that the beam of the moments comes out correctly.  Ugh.  Maybe the right next steps is to make the beam sliceable in the frequency direction and permit `ufuncs` to operate on these values to aggregate as appropriate.

**Comment by keflavich** [comment]
@low-sky I'm working on the spectral-cube side of it now.  It's a pain, but I need it.  The ufunc operation side of things is between tricky and impossible, though, since an array of Beams is not something we can make right now (if you do it, you get a quantity array of steradians).

**Comment by keflavich** [comment]
On the BPA mean side of things - in the current version, I've punted on that entirely, but I'll consider what you've written.  Thing is, the BPA should only affect the tolerance considerations at all if the beam is highly asymmetric.  Maybe I should be doing tolerance checking on the beam area, then on its elongation/rotation....

**Comment by e-koch** [comment]
Is averaging the right thing to do? The [commonbeam](https://casa.nrao.edu/docs/CasaRef/image.commonbeam.html#x36-360001.1.1) tool in CASA seems to be based on finding the minimum enclosing area for all beams in a table (though the wording is rather confusing).

Averaging is probably fine for a first pass right now, given that the changes needed to spectral-cube for this to work are more urgent.

**Comment by low-sky** [comment]
The commonbeam is built with convolution so it would have to be the largest possible beam.  That's appropriate if the images are being convolved up to that resolution.  I think that, without convolution, the average is a relatively sensible reduction of the extra information.

**Comment by keflavich** [comment]
Yes, @low-sky has it right.  We could add an option to convolve to the largest beam, but that's definitely a next step.  I also don't know exactly what that sort of convolution does to the units; "clean" maps have awkward units to begin with (if not all of the flux is cleaned, for example), which might get worse if we start convolving things.

**Comment by e-koch** [comment]
Alright, that makes sense.

I think it does become an issue for manipulating a `VaryingResolutionSpectralCube`, since every moment calculation would need a regrid/convolve to a common resolution (outside of some tolerance threshold; probably only an issue for wide-band cubes).

**Comment by keflavich** [comment]
Yeah, basically `VaryingResolutionSpectralCube`s are going to let you do Bad Things right now, but they'll at least handle io better than at present.  But, regular ol' `SpectralCube`s with average beams (like this one) will work pretty much as advertised, with some added noise.

**Comment by e-koch** [comment]
:+1: 

It would be good to add a stripped down BinTableHDU to the testing data, once you're ready with the spectral-cube side of things.

**Comment by keflavich** [comment]
yeah, workin on it

**Comment by low-sky** [comment]
I think a `ConvolveToCommonBeam` method needs to be there sooner rather than later since that's the only safe operation for combining / comparing cubes with really different beams across them.

**Comment by keflavich** [comment]
@low-sky yeah, but that's still a secondary priority after [reprojection](https://github.com/radio-astro-tools/spectral-cube/pull/289)

**Comment by e-koch** [comment]
Also, for when this becomes a priority, [circular ]

**Comment by keflavich** [comment]
@e-koch what is the circular mean?  From its documentation, I cannot tell what it's doing at all.  I thought it was the mod-90 degrees mean, but it's not.

**Comment by e-koch** [comment]
@keflavich - It should do what @low-sky suggested above (modulo wrapping onto -pi/2 to pi/2). The [wiki](https://en.wikipedia.org/wiki/Directional_statistics#Distribution_of_the_mean) page has a more clear explanation. It should also treat weighting the angles by the `BMAJ`s correctly.

**Comment by keflavich** [comment]
@e-koch ah, the weighting part I hadn't appreciated, that's a good point and I'll use it.  However, I think it is incorrect to think of the circular mean as a modulus based average since it is actually performing a vector average in cartesian space (at least, according to [another wiki article](https://en.wikipedia.org/wiki/Mean_of_circular_quantities)).  I was very confused when I started playing with astropy's circmean when I had assumed it was doing modular arithmetic.

**Comment by keflavich** [comment]
This PR is going to error until we merge some stuff into spectral-cube... maybe.  Now that I think about it more, I'm not sure the changes to spectral-cube will have any effect.  It might just be that `data` can't be imported as a module, even though on my computer it can.  Maybe this has to do with me using the dev version?  But I still don't understand.

**Comment by keflavich** [comment]
OK, this is good to go, I think.  I'd like to merge tomorrow so we can get https://github.com/radio-astro-tools/spectral-cube/pull/292 passing

**Pull request merged**
